name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ODBC driver dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev libodbc2 curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/microsoft.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" \
            | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Bronze tables in Azure SQL
        env:
          SERVER:   ${{ secrets.AZURE_SQL_SERVER }}
          DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          USER:     ${{ secrets.AZURE_SQL_USER }}
          PWD:      ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          python scripts/create_bronze_tables.py

      - name: Run pytest
        env:
          SERVER:   ${{ secrets.AZURE_SQL_SERVER }}
          DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          USER:     ${{ secrets.AZURE_SQL_USER }}
          PWD:      ${{ secrets.AZURE_SQL_PASSWORD }}
        run: pytest -q
