name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ------------------------------------------------------------
  # 1) Test rápidos en Docker (unit tests / no tocan Azure)
  # ------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "DockerSql!2025"
          MSSQL_PID:   "Developer"
        ports:
          - 1433:1433
        # notas: ya no usamos --health-cmd aquí

    steps:
      - uses: actions/checkout@v3

      - name: Install ODBC driver dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
            | sudo apt-key add -
          curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list \
            | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Wait for SQL Server to be ready
        run: |
          echo "Esperando a que SQL Server arranque en el contenedor..."
          for i in {1..30}; do
            nc -z localhost 1433 && echo "¡Listo!" && break
            echo "  intentando conexión... ($i/30)"
            sleep 2
          done

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest against local Docker
        env:
          SERVER: "127.0.0.1,1433"
          DATABASE: "master"
          USER: "SA"
          PWD: "DockerSql!2025"
        run: pytest -q

  # ------------------------------------------------------------
  # 2) Integration tests contra tu Azure SQL real
  # ------------------------------------------------------------
  integration:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/cli@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get public IP of runner
        id: get_ip
        run: echo "RUNNER_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Open firewall for this runner
        run: |
          az sql server firewall-rule create \
            --resource-group ${{ secrets.AZURE_SQL_RESOURCE_GROUP }} \
            --server          ${{ secrets.AZURE_SQL_SERVER_NAME }} \
            --name            GitHubRunner \
            --start-ip-address ${{ env.RUNNER_IP }} \
            --end-ip-address   ${{ env.RUNNER_IP }}

      - name: Install ODBC driver & Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/microsoft.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" \
            | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests against Azure SQL
        env:
          SERVER: ${{ secrets.AZURE_SQL_SERVER_NAME }}.database.windows.net
          DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          USER: ${{ secrets.AZURE_SQL_USER }}
          PWD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: pytest tests/integration -q

      - name: Close firewall for this runner
        if: always()
        run: |
          az sql server firewall-rule delete \
            --resource-group ${{ secrets.AZURE_SQL_RESOURCE_GROUP }} \
            --server          ${{ secrets.AZURE_SQL_SERVER_NAME }} \
            --name            GitHubRunner
